### ISSUE TITLE
Logging config makes wildfly restart each puppet run

### ISSUE THREAD

**Issue by bjwschaap** [xebia-puppet/xebia-wildfly#16]
Each puppet run tries to make a logging configuration, which results in the Wildfly being restarted each puppet run:
```
Notice: /Stage[main]/Wildfly::Config::Logging/Wildfly::Config::Logging_setting[formatter.COLOR-PATTERN.pattern]/Ini_setting[formatter.COLOR-PATTERN.pattern]/value: value changed '%K{level}%d{HH\:mm\:ss,SSS} %-5p [%c] (%t) %s%e%n' to '%K{level}%d{HH\:mm\:ss,SSS} %-5p [%c] (%t) %s%E%n'
Notice: /Stage[main]/Wildfly::Config::Logging/Wildfly::Config::Logging_setting[formatter.PATTERN.pattern]/Ini_setting[formatter.PATTERN.pattern]/value: value changed '%d{yyyy-MM-dd HH\:mm\:ss,SSS} %-5p [%c] (%t) %s%e%n' to '%d{yyyy-MM-dd HH\:mm\:ss,SSS} %-5p [%c] (%t) %s%E%n'
```

**Comment by gntry-io** [comment]
@superseb I'd like to reopen this issue, since the problem appears again on some of our other nodes.

From Wildfly 9 FAQ:
> Why is there a logging.properties file?
> You may have noticed that there is a logging.properties file in the configuration directory. This is
> logging configuration is used when the server boots up until the logging subsystem kicks in. If the
> logging subsystem is not included in your configuration, then this would act as the logging configuration
> for the entire server.
> 
> The logging.properties file is overwritten at boot and with each change to the logging subsystem. Any
> changes made to the file are not persisted. Any changes made to the XML configuration or via
> management operations will be persisted to the logging.properties file and used on the next boot.

In config/loggin.pp the logging.properties file is managed. However, in the profile there's a logging subsystem configuration as well (see: templates/standalone/subsystems/jboss:domain:logging:x.0.xml.erb). 

The logging subsystem makes subtle changes to the logging.properties file during Wildfly boot, causing Puppet to change it, and restart Wildfly, which changes the logging.properties file again, etc. etc...

**Comment by bjwschaap** [comment]
Obviously there are 2 approaches on fixing this:
1. remove logging subsystem configuration
2. remove Puppet managed logging.properties

Although the quick fix would be option 1, and remove the logging subsystem config from the profile, this would make the logging properties totally Puppet managed. Which could be fine, but how about application specific logging settings made by e.g. XLDeploy (for instance a deployable type for log settings)?

I think we should aim for a solution where the initial configuration is made/enforced by Puppet, but then is 'released' (not strictly enforced anymore) by Puppet so other tooling is able to make changes to the logging configuration.

Any ideas/input @superseb @danielpalstra ?

**Comment by sterburg** [comment]
File { replace => false }

**Comment by bjwschaap** [comment]
Thanks for reminding me how Puppet works @sterburg ;-)
I was aiming for a less implementation specific discussion..

**Comment by superseb** [comment]
Complete doc reference @ https://docs.jboss.org/author/display/WFLY9/Logging+Configuration

So we're going for a initial configuration to be able to start WildFly, and let per-deployment-logging handle the rest?

**Comment by bjwschaap** [comment]
@superseb My suggestion is moving the logging properties from the logging.pp out of the manifest into a file (template) resource, and setting replace => false as per @sterburg suggestion. This will:
- prevents the undelying ini_setting mechanism from re-changing the logging properties each run
- allow puppet to set an initial logging.properties file needed for boot-time logging
- allow other tooling to manage the logging properties as well (preferably through the logging subsystem, using Wildfly CLI)

**Comment by bjwschaap** [comment]
As mentioned in #22 I've implemented the logging.properties part, and will create a separate enhancement request / issue for the logging subsystem.
