### ISSUE TITLE
WFLYCTL0309: Legacy extension 'org.jboss.as.threads' is not supported on servers running this version

### ISSUE THREAD

**Issue by bjwschaap** [xebia-puppet/xebia-wildfly#6]
When installing Wildfly 9.0.1 Final, Wildfly fails to boot because the subsystem org.jboss.as.threads is no longer supported. My suggestion is to delete this subsystem from the configuration, since most people probably will want to use Wildfly >= 9

**Comment by superseb** [comment]
As referenced here https://developer.jboss.org/thread/253690?_sscc=t and here https://issues.jboss.org/browse/WFLY-462

**Comment by bjwschaap** [comment]
Seems threads has been deprecated since 7.x:
> threads subsystem was scheduled for removal and as such "internally" deprecated from 7.x times
